### ISSUE TITLE
Update npm Repository

### ISSUE THREAD

**Issue by Novan123** [napolitano/cordova-plugin-intent#27]
Please update 
https://www.npmjs.com/package/cordova-plugin-intent
to the latest release.

**Comment by FdezRomero** [comment]
Hi @Novan123, this plugin is no longer maintained so I guess no more releases will be published to npm. I switched to [darryncampbell-cordova-plugin-intent](https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent) instead.

**Comment by Novan123** [comment]
Thanks.
Topic can be closed. The other Plugin works with npm.

**Comment by rmjspaz** [comment]
@Novan123
